# Generated by Django 4.2.6 on 2023-10-19 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Курсы"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Имя", max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="Фамилия", max_length=100, verbose_name="Фамилия"
                    ),
                ),
                ("age", models.PositiveIntegerField(default=18)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="students/photo", verbose_name="Фото"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Образвание"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=5000, null=True, verbose_name="О себе"
                    ),
                ),
                (
                    "achivments",
                    models.TextField(
                        blank=True,
                        max_length=3000,
                        null=True,
                        verbose_name="Достижения",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
    ]
