# Generated by Django 4.2.6 on 2023-10-19 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(max_length=500, verbose_name="Комментарий"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активен")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-publish"]},
        ),
        migrations.AddField(
            model_name="course",
            name="descriptions",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses", verbose_name="Логотип"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, null=True, unique_for_date="publish"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["-publish"], name="students_co_publish_ef0cba_idx"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="students_co_created_c82060_idx"
            ),
        ),
    ]
