# Generated by Django 4.2.6 on 2023-10-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="books/images/", verbose_name="Обложка"
                    ),
                ),
                (
                    "book",
                    models.FileField(
                        blank=True, upload_to="books/", verbose_name="Книга"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("author", models.CharField(max_length=40, verbose_name="Автор")),
                ("data", models.DateField(verbose_name="Дата публикации")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Литература",
                        to="students.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Литература",
                "verbose_name_plural": "Литература",
                "ordering": ["name"],
            },
        ),
    ]
